version: '3'

services:
  frontend:
    build:
      dockerfile: Dockerfile.frontend
    ports:
      - "4321:4321"

  backend:
    build:
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
